version: '3.8'

services:
  redis:
    image: redis:7
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    dns:
      - 8.8.8.8
      - 1.1.1.1

  backend:
    build: ./backend
    command: flask run --host=${FLASK_RUN_HOST} --port=${FLASK_RUN_PORT}
    volumes:
      - ./backend:/app
    env_file:
      - .env
    expose:
      - "${FLASK_RUN_PORT}"
    depends_on:
      - redis
    dns:
      - 8.8.8.8
      - 1.1.1.1

  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    expose:
      - "3000"
    depends_on:
      - backend   
    dns:
      - 8.8.8.8
      - 1.1.1.1

  worker:
    build: ./backend
    command: rq worker trello-events --url redis://redis:${REDIS_PORT}/0
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - redis
      - backend
    dns:
      - 8.8.8.8
      - 1.1.1.1

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend 