services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    command: flask run --host=0.0.0.0 --port=4001
    env_file:
      - .env.production
    ports:
      - "4001:4001"
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - ./backend/instance:/app/instance
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - FLASK_APP=app.py

  worker:
    build: ./backend
    command: rq worker trello-events --url redis://redis:6379/0
    env_file:
      - .env.production
    depends_on:
      - redis
      - backend
    restart: unless-stopped
    volumes:
      - ./backend/instance:/app/instance
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - FLASK_APP=app.py

volumes:
  redis_data: 